/*
 * File: app/view/SelectionTools.js
 * Date: Tue Dec 04 2012 10:56:58 GMT-0600 (CST)
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SelectionTools', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.selectiontools',

    height: 200,
    width: 300,
    title: 'Selection Tools',
    titleAlign: 'center',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Query',
                    titleAlign: 'center',
                    tabConfig: {
                        xtype: 'tab',
                        minWidth: 75
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                padding: 5,
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    frame: false,
                                    maxWidth: 140,
                                    padding: 5,
                                    allowBlank: false,
                                    displayField: 'type',
                                    forceSelection: true,
                                    store: 'landCoverTypes'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    frame: false,
                                    maxWidth: 140,
                                    padding: 5,
                                    allowBlank: false,
                                    displayField: 'type',
                                    forceSelection: true,
                                    store: 'selectionModification'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    frame: false,
                                    maxWidth: 140,
                                    padding: 5,
                                    store: 'store1'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    frame: false,
                                    maxWidth: 140,
                                    padding: 5,
                                    store: 'store1'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    frame: false,
                                    maxWidth: 140,
                                    padding: 5,
                                    store: 'store1'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    frame: false,
                                    maxWidth: 140,
                                    padding: 5,
                                    store: 'store1'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Manual',
                    tabConfig: {
                        xtype: 'tab',
                        minWidth: 75
                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});