/*
 * File: app/view/TransformationTools.js
 * Date: Tue Nov 27 2012 21:52:50 GMT-0600 (CST)
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TransformationTools', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.transformationtools',

    height: 200,
    width: 300,
    title: 'Transformation Tools',
    titleAlign: 'center',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    bodyPadding: 10,
                    title: 'New Land Cover',
                    items: [
                        {
                            xtype: 'checkboxgroup',
                            width: 400,
                            columns: 1,
                            vertical: true,
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Corn / Soy'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Switchgrass'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'Miscanthus'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Apply'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Revert'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Save'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Options'
                }
            ]
        });

        me.callParent(arguments);
    }

});